<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <p>大概從去年年底我就開始進行從 medium 轉移到這裡的工作，但一路拖到連假才完成這次的搬遷。</p>
    <h2 id="wei4-shen2-me-yao4-li2-kai1-medium">
      <a href="#wei4-shen2-me-yao4-li2-kai1-medium">為什麼要離開 medium ？</a>
    </h2>
    <blockquote>
      <p>
        根本的原因是
        <strong>手癢</strong>
        ，畢竟樂於折騰自己是一個前端工程師的天性。
      </p>
    </blockquote>
    <p>其餘比較實務上的理由就是：</p>
    <ol>
      <li>自己的工作流程</li>
      <li>
        medium 的 <code class="inline-code-block">markdown</code>
         語法支援程度
      </li>
      <li>文章整理</li>
      <li>版面自由度</li>
    </ol>
    <p>
      我自己是先習慣在支援 <code class="inline-code-block">markdown</code>
       的筆記軟體（原本是 notion 現在是 obsidian ）上撰寫後再貼到 medium 。會選擇這樣做的最大理由是在剛開始決定寫文章時我並沒有特別想說要使用哪個平台，所以就先使用筆記軟體撰寫且也方便管理進度或文章種類。
    </p>
    <p>
      但開始使用後就遇到了一些問題，因為 medium 對於 <code class="inline-code-block">markdown</code>
      支援的問題，我直接把從筆記軟體寫好的文章直接貼過去後往往需要稍微修改一下，然後如果看到一些書寫上的小錯誤也會順便修正，但這時我往往會忘記把已經在這邊修正的錯誤貼回去筆記軟體導致這兩個地方的文章不同步，這在當時並不會產生太大的問題頂多就是我在筆記軟體上不一定會是最新的狀態，直到我決定邀遷移出來後才真正造成困擾。因為通常
      medium 的文章我可能還有再次編輯過所以當我在遷移時一定都會是從 medium 複製，但貼到
      <code class="inline-code-block">markdown</code>
       的編輯器，我就又要再修改一次文章。
    </p>
    <p>
      在整理方面medium 的文章 tag 對於分類上沒有太多用處，應該是只有給推薦演算法使用的功能而已。所以沒辦法在 medium
      整理出系列文或者特定類型的文章出來。且對於草稿的管理而言 medium
      也沒有太多著墨，但如果是筆記軟體我就可以手動新增一些tag來輔助我管理。
    </p>
    <h2 id="na4-wo3-zhao3-le-na3-xie1-ti4-dai4-pin3-ne">
      <a href="#na4-wo3-zhao3-le-na3-xie1-ti4-dai4-pin3-ne">那我找了哪些替代品呢？</a>
    </h2>
    <p>在尋找替代品時我有設定幾個需求，能夠滿足愈多點愈好。</p>
    <ol>
      <li>最好是沒碰過的框架</li>
      <li>SSG</li>
      <li>部署的難易程度</li>
      <li>建立環境的難易程度</li>
      <li>一定的自由</li>
    </ol>
    <p>
      所以我大概有考慮過幾個工具： <code class="inline-code-block">next.js</code>
      、
      <code class="inline-code-block">gatsby</code>
      、
      <code class="inline-code-block">svelte-kit</code>
      。
    </p>
    <p>
      首先不選 <code class="inline-code-block">next.js</code>
      的理由是
      <strong>它太強以致於我不想去用</strong>
      ，我需要可能只是我下個指令就可以有一個開箱即用的
      <code class="inline-code-block">markdown</code>
      processor 的環境，且
      <code class="inline-code-block">next.js</code>
      <strong>應該是沒辦法直接把 markdown 當作路由的entry</strong>
      ， 所以我可能還是需要一個
      <code class="inline-code-block">index.tsx</code>
      去載入markdown吧，即使可以使用
      <code class="inline-code-block">index.md</code>
      但應該還是需要額外的套件及開發時間。想想如果我還要額外花時間處理才能讓我享受在其他工具的開發體驗，那我還是直接使用其他工具好了。所以後來就直接不考慮
      <code class="inline-code-block">next.js</code>
       了
    </p>
    <p>
      接下來是 <code class="inline-code-block">gatsby</code>
      做為一個SSG框架，基本上我想要的功能他都能滿足，我也差一點點就決定選擇
      <code class="inline-code-block">gatsby</code>
      直到我找到了
      <code class="inline-code-block">urara</code>
      （一個使用
      <code class="inline-code-block">svelte-kit</code>
      的主題），主要是
      <code class="inline-code-block">urara</code>
      的樣式設計的蠻好看的，再加上是使用
      <code class="inline-code-block">svelte-kit</code>
       我就更有理由選擇他了。
    </p>
    <p>
      但實際用上了之後發現了一點問題，特別是在效能上以及一些無法修正的bug，我就心灰意冷地準備回去使用 <code
        class="inline-code-block">
        gatsby
      </code>
      ，但後來偶然發現
      <code class="inline-code-block">QWER</code>
      一個參考
      <code class="inline-code-block">urara</code>
      的主題，基本上也是作者使用了
      <code class="inline-code-block">urara</code>
       後遇到了某些問題後乾脆自己做了一版。實際用起來雖然還是有一些小問題，但我比較在意的點都已經被解決掉了。
    </p>
    <h2 id="qwer"><a href="#qwer">QWER</a></h2>
    <p>
      首先他的版面設計很對我的味口
      <ImgZoom src="/2023-04-07/QWER-2.jpeg" alt="首頁" class="h-full object-cover" />
    </p>
    <p>
      如果我要新增一篇文章也只要新增一個資料夾以及 <code class="inline-code-block">.md</code>
      檔就好。
      <ImgZoom src="/2023-04-07/QWER-1.png" alt="檔案路由" class="h-full object-cover" />
    </p>
    <p>
      整題而言 <code class="inline-code-block">QWER</code>
       已經滿足我 90% 的需求了，但還是在搬遷時遇到了一些小小問題。
    </p>
    <h2 id="ban1-qian1-guo4-cheng2"><a href="#ban1-qian1-guo4-cheng2">搬遷過程</a></h2>
    <p>如前面提到的大部分的時間都是花在將 medium 的文章貼到 vscode 裡，然後修改一下語法。</p>
    <p>
      而在部署方面我是使用 <code class="inline-code-block">QWER</code>
      文件中推薦的
      <strong>Vercel</strong>
       來部署，基本上也沒多做什麼事情大概就一直按下一步就完成這個網站的部署，整體而言體驗是非常舒服。
    </p>
    <p>
      稍微有改動的程式碼的部分，不知道為什麼在文章頁最後的上下頁的section裡左邊會是下一篇右邊會是上一篇，看起來總是覺得有點怪怪的然後就把他們順序對調了。
    </p>
    <p>
      以及對於 code block 的語言支援程度有限， <code class="inline-code-block">QWER</code>
      是使用
      <code class="inline-code-block">prismjs</code>
      這個 package 作為 processor ，雖然它是有支援我目前有用到的所有語言，但在
      <code class="inline-code-block">QWER</code>
      中並沒有載入某些我有在用的語言，感覺這個部分應該要是在 user config 設定並動態載入所需要語言的 package
      。當然我還是有辦法更改server side部分的code，但這個修改就會在我要更新
      <code class="inline-code-block">QWER</code>
       時被覆蓋掉，所以後來乾脆實作這個語言的dynamic import的功能並開PR回去了。
    </p>
    <p>
      弄的差不多後就想說既然都自己架站了乾脆來處理domain及CDN好了。domain 的話我是在 <strong>google domain</strong>
      上買的，會選擇 google 的原因就只是
      <strong>便宜</strong>
      ，至少我現在這個 domain 在 Vercel 以及cloudflare 都是比在 google 上買還貴，至於 CDN 服務則是用了
      <strong>cloudflare 的免費版</strong>
      。
    </p>
    <p>
      設定上也不會太複雜，在 Vercel 新增新買的 domain，並把 google domain 改用 cloudflare 的 name server 之後在
      cloudflare 新增 Vercel 的 DNS Record 即可。
    </p>
    <h3 id="jie2-yu3"><a href="#jie2-yu3">結語</a></h3>
    <p>
      經過這一陣子的折騰，其實我還是蠻推薦有在寫部落格的人自主架站的，原因是現在有許多好用且免費的服務可以用，除了
      domain 以外我並沒有再花到錢，所以這整個網站的花費不到15美元，算是相當便宜的...吧？
    </p>
    <p>
      而且如果剛好你也是個開發者而且剛好沒接觸過一些網路概念或者架站的知識的話，實際走一次流程還是有一點點收穫的，像我其實也早忘記DNS以及CDN在做什麼，CNAME
      、 A record 又是什麼意思。
    </p>
    <p>
      當然架站也不是只有優點，最大缺點應該會是放棄原本擁有的流量但反正我原本的 medium 也沒什麼人看 <em>(QQ)</em>
       所以這些就當作沒有吧。而且還少了原本部落格平台的 promote ，像是 medium 就會時不時寄信或者 follower 的功能。
    </p>
  </article>
</Post>
