<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <p>
      這系列文主要是重新整理一下今年參加 IT
      邦幫忙鐵人賽的文章，畢竟當初為了趕每日發文的挑戰所以其實有些文章的內容有點水（也可能是我本身就寫得很水xD），如果有興趣的讀者可以參閱一下原本的
      <a href="https://ithelp.ithome.com.tw/users/20159893/ironman/6439" rel="external">系列文</a>
    </p>
    <h2 id="haskell-shi4-shen2-mo2"><a href="#haskell-shi4-shen2-mo2">Haskell 是什麼？</a></h2>
    <p>
      Haskell 是一個非常純粹的函數式程式語言(functional programming
      language)，它所擁有的一些特性讓我們可以寫出更優雅及抽象的程式，例如：first-class function、immutable、lazy
      evaluation、typeclass、currying 等等。
    </p>
    <p>
      但也因為 Haskell
      的特性相較於我們開發上常用的語言來說，它更加的學術且學習曲線更為陡峭，但當我們熟悉這些概念後會發現這些特性會讓我們的開發體驗提升許多。
    </p>
    <h2 id="wei2-shen2-mo2-xiang3-xue2-haskell">
      <a href="#wei2-shen2-mo2-xiang3-xue2-haskell">為什麼想學 Haskell ？</a>
    </h2>
    <p>
      如果有關注這幾年的前端社群風向會發現「FP」這個詞愈來愈常被提到，而且通常會跟「好維護」、「可讀性高」、「難學」等等標籤扯上關係。
    </p>
    <blockquote>
      <p>
        我知道有一派人是對於 point-free 或一直用 <code class="inline-code-block">.</code>
         來 chaing 感到很礙眼，所以可讀性高不高我覺得是見仁見智，但我覺得整份程式碼的確會有一種精緻的感覺。
      </p>
    </blockquote>
    <p>
      但如果要我給一個形容詞來說明 FP 我可能會選擇「優雅」吧，**「我自己感覺」**是在閱讀使用 FP 風格的程式碼較於 OOP
      更好閱讀，雖然我可能看不太懂每個 function 的實作但我大概能從 pipe 的順序去推敲出大概是要做什麼事情。
    </p>
    <blockquote>
      <p>
        特別說明一下，我認為比起 OOP 更好閱讀的原因是因為我覺得 OOP 每一個 class
        該負責多少事情這個範圍很難界定，當然我知道有各種方法論可以幫助我們去釐清依賴的程度及方向，但也許是我剛好沒有跟精通
        OOP 的人一起共事過導致我無法理解 OOP 的精妙
      </p>
    </blockquote>
    <p>
      大概在三年前幸運地下加入到一個非常非常非常非常喜愛 FP 的團隊，熱愛到甚至有用過 PureScript
      來開發產品過。但大部分情況下我們還是使用 ts/js 上開發雖然我們一樣可以盡可能地使用 FP 的特性，但總感覺還是離真正的
      FP 有種隔層紗的感覺。
    </p>
    <p>
      也因此讓我萌生了想要好好學習的 FP 的想法，因為種種原因我直到最近才又開始這項學習計畫。這次既然想要好好學習 FP
      了不如就直接從最純粹的 Haskell 開始吧，所以與其說這個系列文是要學習 Haskell 不如說我真正的目的是要學習 FP 。
    </p>
    <h2 id="kai1-fa1-huan2-jing4"><a href="#kai1-fa1-huan2-jing4">開發環境</a></h2>
    <p>今天先來輕鬆的開發環境設定</p>
    <p>
      因為 Haskell 是一個靜態語言所以我們勢必需要安裝所需要的編譯器，接下來我們都會使用最主流的 GHC (
      <strong>Glasgow Haskell Compiler</strong>
      ) 來進行開發。
    </p>
    <p>
      以下流程皆是使用 <code class="inline-code-block">m1 mac</code>
      及
      <code class="inline-code-block">vs code</code>
      作為示範，但如果沒意外的話各作業系統應該都可以支援 GHCup，特別注意一下
      <code class="inline-code-block">windows</code>
      是需要在
      <code class="inline-code-block">WSL2</code>
       進行安裝。
    </p>
    <h2 id="ghcup"><a href="#ghcup">GHCup</a></h2>
    <p>
      <a href="https://www.haskell.org/ghcup/" rel="external">GHCup</a>
       是一個幫助我們安裝 GHC的工具
    </p>
    <p>接下來我們按照官網的指令輸入：</p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-bash">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token function">curl</span> <span class="token parameter variable">--proto</span> <span class="token string">'=https'</span> <span class="token parameter variable">--tlsv1.2</span> <span class="token parameter variable">-sSf</span> https://get-ghcup.haskell.org <span class="token operator">|</span> <span class="token function">sh</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p>
      基本上就是一路按 <code class="inline-code-block">enter</code>
      就好，但要特別注意的是如果是要使用
      <code class="inline-code-block">vs code</code>
      （其實只要是支援LSP的編輯器）進行開發的讀者，請記得在安裝時記得安裝
      <code class="inline-code-block">Haskell Language Server</code>
    </p>
    <p>然後我們就可以在 terminal 上試用看看 Haskell</p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-bash">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">ghci</div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p>然後我們就可以利用這個環境來讓我們簡單的使用 Haskell 。</p>
    <ImgZoom src="/2023-12-21/ghci-1.png" alt="ghci" class="h-full object-cover" />

    <p>
      如果要退出 gchi 只要輸入 <code class="inline-code-block">:q</code>
       即可
    </p>
    <ImgZoom src="/2023-12-21/ghci-2.png" alt="ghci" class="w-full object-cover" />

    <h3 id="vs-code-she4-ding4"><a href="#vs-code-she4-ding4">vs code設定</a></h3>
    <p>首先推薦安裝幾個 vs code插件</p>
    <ol>
      <li>
        <a href="https://marketplace.visualstudio.com/items?itemName=haskell.haskell" rel="external">Haskell</a>
        <ol>
          <li>提供語法檢查、自動補全等等功能</li>
        </ol>
      </li>
      <li>
        <a href="https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner" rel="external">
          Code Runner
        </a>
        <ol>
          <li>提供更簡單的 build code 流程</li>
        </ol>
      </li>
      <li>
        <a href="https://marketplace.visualstudio.com/items?itemName=hoovercj.haskell-linter" rel="external">
          haskell-linter
        </a>
        <ol>
          <li>程式碼格式檢查</li>
        </ol>
      </li>
      <li>
        <a href="https://marketplace.visualstudio.com/items?itemName=justusadam.language-haskell" rel="external">
          Haskell Syntax Highlighting
        </a>
        <ol>
          <li>語法 hightlight</li>
        </ol>
      </li>
    </ol>
    <p>安裝好後你的 vs code 應該會有類似下面的圖片的功能</p>
    <ImgZoom src="/2023-12-21/vscode-1.png" alt="vscode" class="h-full object-cover" />

    <ImgZoom src="/2023-12-21/vscode-2.png" alt="vscode" class="w-full object-cover" />

    <p>
      特別介紹一下 code runner，安裝好當我們按下右上角的
      <strong>Run Code</strong>
    </p>
    <ImgZoom src="/2023-12-21/vscode-3.png" alt="vscode" class="h-full object-cover" />

    <p>會直接在下方的 Output 顯示執行結果</p>
    <ImgZoom src="/2023-12-21/vscode-4.png" alt="vscode" class="h-full object-cover" />

    <h3 id="ke3-neng2-hui4-yu4-dao4-keng1"><a href="#ke3-neng2-hui4-yu4-dao4-keng1">可能會遇到坑</a></h3>
    <p>如果出現以下錯誤</p>
    <p>
      <code class="inline-code-block">
        Consider installing HLS via ghcup or change &quot;haskell.manageHLS&quot; in your settings
      </code>
    </p>
    <p>
      可以試著先看一下自己的 vs code <code class="inline-code-block">setting.json</code>
      是否有
      <code class="inline-code-block">haskell.manageHLS</code>
       的設定
    </p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-json">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">"haskell.manageHLS": "GHCup",</div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p>
      如果還是沒辦法，可以試著用 <code class="inline-code-block">cabal</code>
      安裝
      <code class="inline-code-block">haskell-language-server</code>
       看看
    </p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-bash">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">ghcup <span class="token function">install</span> cabal <span class="token number">3.10</span>.1.0</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">cabal <span class="token function">install</span> haskell-language-server</div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p>如果遇到 linter相關的</p>
    <p>
      可以看一下
      <code class="inline-code-block">setting.json</code>
       有無設定：
    </p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-json">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">"haskell.hlint.executablePath": "hlint",</div></div>`}</code></pre>
      </CodeCopy>
    </div>
  </article>
</Post>
