<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="hi-wo3-shi4-todd"><a href="#hi-wo3-shi4-todd">HI 我是 Todd</a></h1>
    <p>歡迎來到我的 blog ，其實我一直不太會自我介紹，所以就乾脆列了份清單讓你快速知道我是一個怎麼樣的人</p>
    <ul>
      <li>名字是來自於我很喜歡的影集馬男波傑克（Bojack Horseman）中的 Todd</li>
      <li>INFP-T，雖然我認為將人劃分成 16 種人感覺太武斷了，但或許這是別人有辦法快速認識我的好方法</li>
      <li>
        喜歡攝影，目前主力機器是 Fujifilm 的 XT-30 II ，第一台數位相機是 D7000 ，第一台底片相機是
        FM3A，擁有的機身中最喜歡 Bronica S2，預計未來會回到 N 家的懷抱
      </li>
      <li>
        聽的音樂相當雜食，前十喜歡的樂團、歌手、樂手或者音樂人大概是：Radiohead、魚韻、滅火器、ヨルシカ、wowaka、ZTMY、RADWIMPS、DECO*27、角野隼斗、Orangestar
      </li>
      <li>熱愛日本文化，目前正在自學日文中</li>
      <li>喜歡看棒球，但大多數時候是戰績寄生迷沒特別支持哪一隊</li>
      <li>喜歡吃甜點特別是抹茶相關的</li>
      <li>
        每天都喝咖啡，但最近很懶的手沖會乾脆喝超商咖啡或者泡咖樂迪濾袋冷萃咖啡，之前比較喜歡的豆子是淺中焙的日曬處理的帕拉伊內瑪，不喜歡酸味突出的咖啡。
      </li>
      <li>也喜歡喝茶，比較喜歡綠茶烏龍也還可以但紅茶不太行，最近為了好睡下午之後只會喝麥茶</li>
      <li>目前的職業是網頁全端工程師，雖說是目前但無意外的話以後也應該會繼續往全端發展</li>
      <li>喜歡 FP 遠大於 OOP</li>
      <li>工作上最常使用 React 、 TypeScript 和 Node.js</li>
      <li>小專案喜歡使用 Svelte</li>
      <li>最喜歡的程式語言是 Haskell</li>
      <li>最討厭的程式語言是 JavaScript，但它是世界上最好的語言</li>
    </ul>
  </article>
</Post>
