<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <p>
      hi ， 我是 Todd 目前在 Ionex 擔任 software engineer ，工作上主要使用 react + TypeScript 進行網頁前端開發以及
      express 開發網頁後端，平常喜歡研究一些新技術及工具。
    </p>
    <h2 id="mu4-qian2-zhu3-yao4-shi3-yong4-de-ji4-shu4">
      <a href="#mu4-qian2-zhu3-yao4-shi3-yong4-de-ji4-shu4">目前主要使用的技術</a>
    </h2>
    <p>以下是我平常目前工作會遇到或者自己寫一些小專案時會用到的技術</p>
    <h3 id="qian2-duan1-xiang1-guan1"><a href="#qian2-duan1-xiang1-guan1">前端相關</a></h3>
    <ul>
      <li>TypeScript</li>
      <li>
        react
        <ul>
          <li>next.js</li>
          <li>react-query, apollo-client</li>
          <li>jotai</li>
          <li>react-router</li>
          <li>react-hook-form</li>
          <li>
            redux
            <ul>
              <li>redux-toolkit, redux-thunk, redux-saga</li>
            </ul>
          </li>
        </ul>
      </li>
      <li>mui, taillwind</li>
      <li>vite, webpack</li>
      <li>storybook</li>
      <li>jest, react-testing-library, playwright</li>
    </ul>
    <h3 id="hou4-duan1-huo4-wei2-yun4-xiang1-guan1">
      <a href="#hou4-duan1-huo4-wei2-yun4-xiang1-guan1">後端或維運相關</a>
    </h3>
    <ul>
      <li>Node.js, express</li>
      <li>MongoDB</li>
      <li>apollo-server</li>
      <li>
        AWS
        <ul>
          <li>主要使用 S3 及 cloudfront</li>
        </ul>
      </li>
      <li>Jenkins</li>
      <li>Docker</li>
      <li>github actions</li>
      <li>vercel</li>
      <li>cloudflare</li>
    </ul>
    <h2 id="zui4-jin4-zai4-yan2-jiu1-de-dong1-xi1">
      <a href="#zui4-jin4-zai4-yan2-jiu1-de-dong1-xi1">最近在研究的東西</a>
    </h2>
    <ul>
      <li>svelte</li>
      <li>rust</li>
      <li>
        haskell
        <ul>
          <li>
            最近剛完成鐵人賽，
            <a href="https://ithelp.ithome.com.tw/users/20159893/ironman/6439" rel="external">系列文</a>
            主題是關於 haskell 入門，有興趣的話可以參閱看看。
          </li>
        </ul>
      </li>
    </ul>
    <h2 id="qi2-ta1-yi3-qian2-yong4-guo4-dan4-xian4-zai4-gong1-zuo4-shang4-hen3-shao3-yong4-dao4-de-ji4-shu4">
      <a href="#qi2-ta1-yi3-qian2-yong4-guo4-dan4-xian4-zai4-gong1-zuo4-shang4-hen3-shao3-yong4-dao4-de-ji4-shu4">
        其他以前用過但現在工作上很少用到的技術
      </a>
    </h2>
    <ul>
      <li>styled-components</li>
      <li>gatsby</li>
      <li>ant-design</li>
      <li>chakra-ui</li>
      <li>flutter</li>
      <li>jQuery</li>
      <li>bootstrap</li>
      <li>scss/sass</li>
      <li>pug</li>
    </ul>
  </article>
</Post>
